# Generated by Django 3.2.6 on 2021-09-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('commandDate', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CommandRow',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('quantityOrdered', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('deliveryDate', models.DateTimeField(auto_now_add=True)),
                ('totalProductDelivered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(default='', max_length=1500)),
                ('unitPrice', models.FloatField()),
                ('stockUnit', models.CharField(choices=[('U', 'U'), ('FF', 'Ff'), ('ml', 'Ml'), ('m2', 'M2'), ('m3', 'M3'), ('L', 'L')], default='U', max_length=20)),
                ('stockQuantity', models.FloatField()),
                ('alertThreshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('quantityDelivered', models.IntegerField()),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('commandRow', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.commandrow')),
                ('delivery', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='commandRows',
            field=models.ManyToManyField(related_name='deliveries', through='api.DeliveryDetails', to='api.CommandRow'),
        ),
    ]
