# Generated by Django 3.2.6 on 2021-09-05 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='received_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandrow',
            name='command',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.command'),
        ),
        migrations.AddField(
            model_name='commandrow',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='command',
            name='command_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='command',
            name='products',
            field=models.ManyToManyField(related_name='commands', through='api.CommandRow', to='api.Product'),
        ),
    ]
