# Generated by Django 3.2.6 on 2021-09-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='totalProductDelivered',
        ),
    ]
